import './globals.css'
import { Header } from './components/Headers'

export const metadata = {
  title: 'IMDb-Clone',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
          <Header />
          {children}
      </body>
    </html>
  )
}
