import "./globals.css";
import { Header } from "./components/header";
import { Providers } from "./providers";
import { Navbar } from "./components/Navbar";
import { AuthContextProvider } from "@/context/AuthContext";

export const metadata = {
  title: "IMDb-Clone",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Providers>
            <Header />
            <Navbar />
            {children}
          </Providers>
        </AuthContextProvider>
      </body>
    </html>
  );
}
